"""Added path column to fetch video

Revision ID: dd4a3444e9f6
Revises: e83dab35bf12
Create Date: 2019-06-25 12:23:53.508585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4a3444e9f6'
down_revision = 'e83dab35bf12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('path', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'path')
    # ### end Alembic commands ###
